# Generated by Django 5.0.3 on 2024-03-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('issued', models.DateField()),
                ('title', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('authors', models.TextField()),
                ('subjects', models.TextField()),
                ('locc', models.CharField(max_length=255, verbose_name='LoCC')),
                ('bookshelves', models.TextField()),
            ],
        ),
    ]
