# Generated by Django 5.0.3 on 2024-03-11 13:50

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess', '0002_indextable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordFrequencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_frequencies', to='preprocess.book')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencies', to='preprocess.word')),
            ],
            options={
                'unique_together': {('book', 'word')},
            },
        ),
        migrations.CreateModel(
            name='WordPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_positions', to='preprocess.book')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='preprocess.word')),
            ],
            options={
                'unique_together': {('book', 'word')},
            },
        ),
    ]
