# Generated by Django 5.0.3 on 2024-03-11 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess', '0003_word_wordfrequencies_wordpositions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indextable',
            unique_together={('book', 'word')},
        ),
        migrations.AddField(
            model_name='indextable',
            name='betweenness_centrality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='indextable',
            name='closeness_centrality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='indextable',
            name='pagerank',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='indextable',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_metrics', to='preprocess.book'),
        ),
        migrations.AlterField(
            model_name='indextable',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='preprocess.word'),
        ),
        migrations.RemoveField(
            model_name='indextable',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='indextable',
            name='position',
        ),
    ]
