# Generated by Django 5.0.3 on 2024-03-12 21:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess', '0004_alter_indextable_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacencyList',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='preprocess.book')),
                ('adjacent_book_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='EdgeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('source_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_edges', to='preprocess.book')),
                ('target_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_edges', to='preprocess.book')),
            ],
        ),
    ]
