# Generated by Django 5.0.3 on 2024-03-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess', '0005_adjacencylist_edgelist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indextable',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='indextable',
            name='word',
        ),
    ]
